package com.longdx.silre_backend.service.impl;

import com.longdx.silre_backend.dto.request.CreateUserRequest;
import com.longdx.silre_backend.dto.response.UserResponse;
import com.longdx.silre_backend.model.User;
import com.longdx.silre_backend.repository.UserRepository;
import com.longdx.silre_backend.service.UserService;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.Optional;

/**
 * Service implementation for User operations
 * 
 * Pattern:
 * - @Service annotation
 * - @Transactional for write operations
 * - Inject repositories and utilities
 * - Handle business logic
 * - Map entities to DTOs
 */
@Service
@Transactional
public class UserServiceImpl implements UserService {

    private final UserRepository userRepository;
    private final PasswordEncoder passwordEncoder;
    // TODO: Add NanoID generator and TSID factory when needed

    public UserServiceImpl(UserRepository userRepository, PasswordEncoder passwordEncoder) {
        this.userRepository = userRepository;
        this.passwordEncoder = passwordEncoder;
    }

    @Override
    public UserResponse createUser(CreateUserRequest request) {
        // Check if email already exists
        if (userRepository.existsByEmail(request.email())) {
            throw new IllegalArgumentException("Email already exists: " + request.email());
        }

        // Create new user entity
        User user = new User();
        user.setDisplayName(request.displayName());
        user.setEmail(request.email());
        user.setPasswordHash(passwordEncoder.encode(request.password()));
        
        // TODO: Generate public_id (NanoID) and internal_id (TSID)
        // For now, set placeholder values
        user.setPublicId("PLACEHOLDER"); // Will be generated
        user.setInternalId(1L); // Will be generated by TSID

        // Save user
        User savedUser = userRepository.save(user);

        // Return DTO
        return UserResponse.from(savedUser);
    }

    @Override
    @Transactional(readOnly = true)
    public Optional<UserResponse> getUserByPublicId(String publicId) {
        return userRepository.findByPublicId(publicId)
                .map(UserResponse::from);
    }

    @Override
    @Transactional(readOnly = true)
    public Optional<User> getUserByEmail(String email) {
        return userRepository.findByEmail(email);
    }

    @Override
    public UserResponse updateProfile(String publicId, String displayName, String bio) {
        User user = userRepository.findByPublicId(publicId)
                .orElseThrow(() -> new IllegalArgumentException("User not found: " + publicId));

        if (displayName != null) {
            user.setDisplayName(displayName);
        }
        if (bio != null) {
            user.setBio(bio);
        }

        User updatedUser = userRepository.save(user);
        return UserResponse.from(updatedUser);
    }

    @Override
    @Transactional(readOnly = true)
    public boolean emailExists(String email) {
        return userRepository.existsByEmail(email);
    }
}



